# Makefile.deps created Fri May 20 16:38:28 PDT 2016 by make
astree.o: astree.cpp astree.h auxlib.h stringset.h lyutils.h yyparse.h
lyutils.o: lyutils.cpp lyutils.h astree.h auxlib.h yyparse.h
stringset.o: stringset.cpp stringset.h
auxlib.o: auxlib.cpp auxlib.h
oc.o: oc.cpp auxlib.h stringset.h lyutils.h astree.h yyparse.h
yylex.o: yylex.cpp auxlib.h lyutils.h astree.h yyparse.h
yyparse.o: yyparse.cpp lyutils.h astree.h auxlib.h yyparse.h
